spring:
  application:
    name: merchant
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 939916800727-pdmvqks4go07af20cf9d3vnodu4i8721.apps.googleusercontent.com
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            issuer-uri: https://accounts.google.com

  ssl:
    bundle:
      jks:
        server:
          keystore:
            location: classpath:keystore/merchant.jks
            password: kwxy4o1
            type: PKCS12

server:
  port: 8443
  ssl:
    bundle: server

custom.security:
  oauth2:
    redirect-url: http://localhost:5173/auth/callback
    jwt-secret: kwlvIo30PkalqxZmTeklspOgfrTKFMDsuQzwBE39tzPqmsedyakfhjOAU
    jwt-expiry: 30
  token:
    password: mmakprjshson782nndkgfakofbvbbaos909akamm2904jopashjfmsajkfkobhfdyftqdwj
#https://medium.com/@AlexanderObregon/cookie-based-auth-in-spring-boot-without-using-sessions-d795c1d530e0
server.servlet.session.cookie:
  http-only: true
  secure: true
  same-site: none
  domain: localhost

